# -*- mode: python ; coding: utf-8 -*-

import os

# Conda installs PySide2 with _conda.dll suffix variants.
# PyInstaller does not auto-detect them, so we list them explicitly.
_conda_bin = r'C:\Users\abdelmageed.fathy\AppData\Local\miniconda3\envs\laplis\library\bin'
_pyside2_dir = r'C:\Users\abdelmageed.fathy\AppData\Local\miniconda3\envs\laplis\lib\site-packages\PySide2'
_shiboken2_dir = r'C:\Users\abdelmageed.fathy\AppData\Local\miniconda3\envs\laplis\lib\site-packages\shiboken2'

_conda_dlls = [
    'Qt5Core_conda.dll',
    'Qt5Gui_conda.dll',
    'Qt5Widgets_conda.dll',
    'Qt5Charts_conda.dll',
    'Qt5Svg_conda.dll',
    'Qt5Network_conda.dll',
    'pyside2.cp39-win_amd64.dll',
    'shiboken2.cp39-win_amd64.dll',
]

_extra_binaries = [
    (os.path.join(_conda_bin, dll), '.') for dll in _conda_dlls
    if os.path.exists(os.path.join(_conda_bin, dll))
]

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=_extra_binaries,
    datas=[('app/seed_data', 'app/seed_data'), ('app/reports/fonts', 'app/reports/fonts'), ('logo', 'logo')],
    hiddenimports=[
        'PySide2',
        'PySide2.QtCore',
        'PySide2.QtGui',
        'PySide2.QtWidgets',
        'PySide2.QtCharts',
        'PySide2.QtSvg',
        'bcrypt',
        'sqlite3',
        'arabic_reshaper',
        'bidi',
        'bidi.algorithm',
        # reportlab – all submodules used by dynamic imports
        'reportlab',
        'reportlab.graphics',
        'reportlab.graphics.barcode',
        'reportlab.graphics.barcode.code128',
        'reportlab.graphics.barcode.code39',
        'reportlab.graphics.barcode.code93',
        'reportlab.graphics.barcode.common',
        'reportlab.graphics.barcode.dmtx',
        'reportlab.graphics.barcode.eanbc',
        'reportlab.graphics.barcode.ecc200datamatrix',
        'reportlab.graphics.barcode.fourstate',
        'reportlab.graphics.barcode.lto',
        'reportlab.graphics.barcode.qr',
        'reportlab.graphics.barcode.qrencoder',
        'reportlab.graphics.barcode.usps',
        'reportlab.graphics.barcode.usps4s',
        'reportlab.graphics.barcode.widgets',
        'reportlab.graphics.charts',
        'reportlab.graphics.charts.areas',
        'reportlab.graphics.charts.barcharts',
        'reportlab.graphics.charts.legends',
        'reportlab.graphics.charts.linecharts',
        'reportlab.graphics.charts.lineplots',
        'reportlab.graphics.charts.piecharts',
        'reportlab.graphics.charts.textlabels',
        'reportlab.graphics.renderPDF',
        'reportlab.graphics.renderPM',
        'reportlab.graphics.renderSVG',
        'reportlab.graphics.shapes',
        'reportlab.graphics.widgetbase',
        'reportlab.lib',
        'reportlab.lib.colors',
        'reportlab.lib.enums',
        'reportlab.lib.fonts',
        'reportlab.lib.pagesizes',
        'reportlab.lib.styles',
        'reportlab.lib.units',
        'reportlab.lib.utils',
        'reportlab.pdfbase',
        'reportlab.pdfbase._fontdata',
        'reportlab.pdfbase._fontdata_enc_winansi',
        'reportlab.pdfbase._fontdata_enc_macroman',
        'reportlab.pdfbase._fontdata_enc_standard',
        'reportlab.pdfbase._fontdata_enc_symbol',
        'reportlab.pdfbase._fontdata_enc_zapfdingbats',
        'reportlab.pdfbase._fontdata_widths_courier',
        'reportlab.pdfbase._fontdata_widths_courierbold',
        'reportlab.pdfbase._fontdata_widths_courierboldoblique',
        'reportlab.pdfbase._fontdata_widths_courieroblique',
        'reportlab.pdfbase._fontdata_widths_helvetica',
        'reportlab.pdfbase._fontdata_widths_helveticabold',
        'reportlab.pdfbase._fontdata_widths_helveticaboldoblique',
        'reportlab.pdfbase._fontdata_widths_helveticaoblique',
        'reportlab.pdfbase._fontdata_widths_symbol',
        'reportlab.pdfbase._fontdata_widths_timesbold',
        'reportlab.pdfbase._fontdata_widths_timesbolditalic',
        'reportlab.pdfbase._fontdata_widths_timesitalic',
        'reportlab.pdfbase._fontdata_widths_timesroman',
        'reportlab.pdfbase._fontdata_widths_zapfdingbats',
        'reportlab.pdfbase.pdfdoc',
        'reportlab.pdfbase.pdfmetrics',
        'reportlab.pdfbase.pdfutils',
        'reportlab.pdfbase.ttfonts',
        'reportlab.pdfgen',
        'reportlab.pdfgen.canvas',
        'reportlab.pdfgen.pathobject',
        'reportlab.pdfgen.textobject',
        'reportlab.platypus',
        'reportlab.platypus.doctemplate',
        'reportlab.platypus.flowables',
        'reportlab.platypus.frames',
        'reportlab.platypus.paragraph',
        'reportlab.platypus.tables',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='mostafa elznaty',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['logo\\app_icon.ico'],
)
